# Generated by Django 3.2.4 on 2021-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('COMPLETE', 'COMPLETE')], default='NEW', max_length=30),
        ),
    ]
